#!/bin/sh
# martin, 2018-12-20, 2019-01-12, 2019-11-17, 2019-11-19, 2022-03-24
# locates and prints committer info from .git/config

NAME=$(git config --get user.name)
EMAIL=$(git config --get user.email)

echo "${NAME} <${EMAIL}>"
