#!/usr/bin/env perl

# martin, 2019-03-20
# probes if the client is connected to mullvad.net

use strict;
use warnings;
use v5;

use JSON::PP qw[decode_json];

my $probe_url = 'https://am.i.mullvad.net/json';
my @curl = qw[curl -s]; # /bin/curl, etc.

sub main {
  binmode(STDIN,  ':utf8');
  binmode(STDOUT, ':utf8');
  binmode(STDERR, ':utf8'); 

  my $json = qx[@curl $probe_url];
  die "fail: $?" unless $? == 0;

  my %res = %{decode_json($json)};

  unless ($res{mullvad_exit_ip}) {
    print "Not connected through Mullvad ($res{ip})\n";
    exit;
  }

  print "Connected to Mullvad "
      ."($res{ip}) ($res{city}, $res{country})\n";
}

main;
