#!/usr/bin/env perl
# martin, 2018-09-02, 2018-12-19, 2019-10-21
# ./spacer hello => "h e l l o"
# ./spacer -meme hello => "ｈｅｌｌｏ"
# ./spacer -sponge i'm the bad guy... duh! => "i'm thE baD gUY... DUh!"

use strict;
use warnings;
use utf8;

binmode(STDIN, ':utf8');
binmode(STDOUT, ':utf8');
binmode(STDERR, ':utf8');

sub spaced {
  s/([^\s])/$1 /gr . "  "
}

sub fullwidth {
  my $delta = ord('！') - ord('!');
  my $fw = join('',  map { chr(ord($_) + $delta) } split(//, $_[0]));
  return $fw;
}

sub spongecase {
  return
      join '',
      map { rand >= 0.5 ? uc $_ : lc $_ }
      split //, $_[0];
}

if ($ARGV[0] =~ /--?meme/) {
  print fullwidth($_), " " for @ARGV[1..$#ARGV];
} elsif ($ARGV[0] =~ /--?sponge/) {
  print spongecase($_), " " for @ARGV[1..$#ARGV];
} else {
  print spaced($_) for @ARGV;
}
print "\n";
